services:
  # Nginx reverse proxy
  oneserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oneserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${ONESERVER_PWD:-.}/cert:/etc/nginx/ssl:ro
      - ${ONESERVER_PWD:-.}/nginx-logs:/var/log/nginx
    restart: unless-stopped
    networks:
      - oneserver_bridge

networks:
  oneserver_bridge:
      name: oneserver_bridge

# to add servers to the network, add the following to the server's container service definition:
# networks:
#   - oneserver_bridge

# and connect the compose project to the bridge network with the following configuration:
# networks:
#   oneserver_bridge:
#     external: true